### ISSUE TITLE
Speakers are not centered in mobile view, add spacing instead of overlay expansion

### ISSUE THREAD

**Issue by mariobehling** [OpnTec/vn.opentechsummit.asia#33]
The overlay area is expanded which resulted in a 3 column speaker area. Please implement this area with space instead of padding.

Also ensure this works on mobile view.

![Screenshot from 2019-10-08 09-02-11](https://user-images.githubusercontent.com/1583873/66362020-5b2f0b80-e9ab-11e9-9699-de97e07a9ed8.png)

**Comment by skarthikeyan96** [comment]
@mariobehling 

![scrnli_10_8_2019_11-51-32 AM](https://user-images.githubusercontent.com/23126394/66371824-195d8f80-e9c2-11e9-97fc-658c37277131.png)

Is this expected? does this look okay in mobile view?

**Comment by mariobehling** [comment]
Looks ok, but it is difficult to discuss things without a PR. Please make a PR, so someone can provide input. Thanks.

**Comment by skarthikeyan96** [comment]
Sure @mariobehling will raise PR

**Comment by fcartegnie** [comment]
Also check input with w3 validator.
I already had to handle earlier issues with that part which was not edited with proper tools,
there's potentially still invisible unicode sequences breaking the layout.

**Comment by skarthikeyan96** [comment]
sure will do as well. Thanks fcartegnie.

**Comment by fcartegnie** [comment]
@skarthikeyan96 I did a PR for validation fixes. Was borken html everywhere
https://github.com/OpnTec/vn.opentechsummit.asia/pull/34

**Comment by skarthikeyan96** [comment]
I ran w3c validation check again still errors are there.

**Comment by fcartegnie** [comment]
> I ran w3c validation check again still errors are there.

Yes, the whole set was reverted because of some local regressions

you can still use my commits https://github.com/fcartegnie/vn.opentechsummit.asia

**Comment by skarthikeyan96** [comment]
oh okay will take a  look

**Comment by skarthikeyan96** [comment]
Fixed the speakers display for now , have to go through the w3c validation errors 

@mariobehling

**Comment by kumuditha-udayanga** [comment]
@mariobehling Changes has been done :) #53
